version: '3.0'
services:
  postgres:
    image: postgres:latest
    container_name: pgecotecno
    environment:
        TZ: "Europe/Rome"
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: ecotecno
        POSTGRES_DB: ecotecnodb
    ports:
    - '65432:5432'
    logging:
      driver: "json-file"
      options:
        max-size: "50m"


  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    entrypoint: redis-server --appendonly yes


  django_migrate:
    image: cecilio91/ecotecno:v1django
    container_name: djangobackup
    ports:
      - '38400:8000'
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    environment:
        EJECUTAR: 'python3 manage.py migrate'


  django:
    image: cecilio91/ecotecno:v1django
    container_name: djangobackup
    ports:
      - '38400:8000'
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    environment:
        EJECUTAR: 'python3 manage.py runserver 0.0.0.0:8000'
