apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file backend.yml convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: django
  name: django
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: django
    spec:
      containers:
      - env:
        - name: EJECUTAR
          value: python3 manage.py runserver 0.0.0.0:8000
        image: cecilio91/ecotecno:v1django
        name: djangobackup
        ports:
        - containerPort: 8000
        resources: {}
      restartPolicy: Always
status: {}
