apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file backend.yml convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: django-migrate
  name: django-migrate
spec:
  ports:
  - name: "38400"
    port: 38400
    targetPort: 8000
  selector:
    io.kompose.service: django-migrate
status:
  loadBalancer: {}
