apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file backend.yml convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: postgres
  name: postgres
spec:
  ports:
  - name: "65432"
    port: 65432
    targetPort: 5432
  selector:
    io.kompose.service: postgres
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file backend.yml convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: postgres
  name: postgres
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: postgres
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: ecotecnodb
        - name: POSTGRES_PASSWORD
          value: ecotecno
        - name: POSTGRES_USER
          value: postgres
        - name: TZ
          value: Europe/Rome
        image: postgres:latest
        name: pgecotecno
        ports:
        - containerPort: 5432
        resources: {}
      restartPolicy: Always
status: {}
