apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: postgres
  POSTGRES_USER: ecotecnodb
  POSTGRES_PASSWORD: ecotecno
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim
  labels:
    app: postgres
spec:
  storageClassName: cdk-cinder
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  hostPath:
    path: "/mnt/data"
