apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file backend.yml convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: postgres
  name: postgres
spec:
  ports:
  - name: "65432"
    port: 65432
    targetPort: 5432
  selector:
    io.kompose.service: postgres
status:
  loadBalancer: {}
