# Generated by Django 2.2.3 on 2019-11-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='placesAvailable',
        ),
        migrations.RemoveField(
            model_name='service',
            name='placesOccupied',
        ),
        migrations.RemoveField(
            model_name='service',
            name='radius',
        ),
        migrations.AddField(
            model_name='service',
            name='IoTdevice',
            field=models.CharField(default='italy', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='unit',
            field=models.CharField(default='°C', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='value',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
