# Generated by Django 2.2.3 on 2019-11-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_auto_20191106_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='SensorType',
            field=models.CharField(default='temperture', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='IoTdevice',
            field=models.CharField(default='WioLink', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='city',
            field=models.CharField(blank=True, default='milano', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='country',
            field=models.CharField(blank=True, default='italy', max_length=60, null=True),
        ),
    ]
