# Generated by Django 2.2.3 on 2019-11-06 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_auto_20191106_0838'),
        ('location', '0003_auto_20191106_0756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='service',
            name='longitude',
        ),
        migrations.AddField(
            model_name='service',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seller.profile'),
        ),
    ]
