---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: data-injector
    app.kubernetes.io/component: data-injector
    app.kubernetes.io/version: "1"
  name: data-injector
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: data-injector
      app.kubernetes.io/version: "1"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: data-injector
        app.kubernetes.io/component: data-injector
        app.kubernetes.io/version: "1"
    spec:
      containers:
      - image: aletundo/htc19-data-injector:v1
        imagePullPolicy: Always
        name: data-injector
        command: ["python"]
        args: ["senddata.py", "$(API_URL)"]
        env:
        - name: API_URL
          value: http://90.147.184.214
