---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: django-api
    app.kubernetes.io/component: api
    app.kubernetes.io/version: "1"
  name: django-api
spec:
  ports:
  - name: django-api
    port: 80
    targetPort: django-api
  # type: ClusterIP
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: django-api
    app.kubernetes.io/version: "1"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: django-api
    app.kubernetes.io/component: api
    app.kubernetes.io/version: "1"
  name: django-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: django-api
      app.kubernetes.io/version: "1"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: django-api
        app.kubernetes.io/component: api
        app.kubernetes.io/version: "1"
    spec:
      containers:
      - env:
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: db_url
        image: cecilio91/ecotecno:v1django
        imagePullPolicy: Always
        name: django-api
        command: ["python"]
        args: ["manage.py", "runserver", "0.0.0.0:8000"]
        ports:
        - name: django-api
          containerPort: 8000
