---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/component: frontend
    app.kubernetes.io/version: "1"
  name: frontend
spec:
  ports:
  - name: frontend
    port: 80
    targetPort: frontend
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/version: "1"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/component: frontend
    app.kubernetes.io/version: "1"
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: frontend
      app.kubernetes.io/version: "1"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: frontend
        app.kubernetes.io/component: frontend
        app.kubernetes.io/version: "1"
    spec:
      containers:
      - env:
        - name: SERVICE_PORT
          value: "5000"
        - name: API_URL
          value: http://django-api
        - name: VUE_APP_MAPS_KEY
          valueFrom:
            secretKeyRef:
              name: frontend-secret
              key: VUE_APP_MAPS_KEY
        image: crisbal/htc19
        imagePullPolicy: Always
        name: frontend
        ports:
        - name: frontend
          containerPort: 5000