# Generated by Django 2.2.3 on 2019-11-06 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(blank=True, default='italy', max_length=60, null=True)),
                ('description', models.CharField(default='description', max_length=250, null=True)),
                ('image', models.FileField(unique=True, upload_to='scripts/')),
            ],
        ),
        migrations.CreateModel(
            name='seller_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product', models.ManyToManyField(to='product.product')),
            ],
        ),
    ]
