# Generated by Django 2.2.3 on 2019-11-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20191106_0907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AlterField(
            model_name='product',
            name='product',
            field=models.CharField(blank=True, default='Pomodoro', max_length=60, null=True),
        ),
    ]
