# Generated by Django 2.2.3 on 2019-11-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20191106_0917'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='description', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.FileField(default=2, unique=True, upload_to='scripts/'),
            preserve_default=False,
        ),
    ]
