# Generated by Django 2.2.3 on 2019-11-06 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_auto_20191106_1036'),
        ('product', '0006_auto_20191106_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller_product',
            name='Products',
        ),
        migrations.RemoveField(
            model_name='seller_product',
            name='seller',
        ),
        migrations.AddField(
            model_name='seller_product',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AddField(
            model_name='seller_product',
            name='sellers',
            field=models.ManyToManyField(to='seller.profile'),
        ),
    ]
