# Generated by Django 2.2.3 on 2019-09-12 02:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0003_auto_20190910_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estados',
            name='FechaTurno',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 11, 14, 30)),
        ),
        migrations.AlterField(
            model_name='estados_inicial',
            name='FechaTurno',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 11, 14, 30)),
        ),
    ]
